fov_h: 0.7592  # [rad]
epsilon: 0.7
pole_0: -2.5
kappa: 70
gamma: 40
alpha: 2
fov_alpha: 6
fov_slack: 200
lp_gain_in: 0.4
lp_gain_out: 0.6
clamp_xy: 3
clamp_z: 3
gain_x: 1
gain_y: 1
gain_z: 3
output_frame_viz: rmf_owl/base_link
analytical_sol: true
ctrl_freq: 100
obs_to: 1  # obstacle timeout [sec]
cmd_to: 1  # command timeout [sec]
